### ISSUE TITLE
Add parameter selection to main dialog

### ISSUE THREAD

**Issue by lehtojaa** [GispoCoding/FMI2QGIS#1]
Main dialog should have option for the user to select what measurement data is loaded.

Possible parameters:
- air quality index (AQI)
- Nitrogen dioxide concentration (NO2Concentration)
- Ozone concentration (O3Concentration)
- Concentration of particles smaller than 10 micrometres (PM10Concentration)
- Concentration of particles smaller than 2.5 micrometres (PM10Concentration)

This could be implemented as checkboxes with a default configuration (only AQI checked?)

**Comment by Joonalai** [comment]
Also add:
* output directory: QgsFileEdit 
* starttime: QgsDateTimeEdit
* endtime: QgsDateTimeEdit
* bounding box: QgsExtentGroupBox 
* To the bottom GroupBox containing attribution information (copyrights, links etc.)

Remove:
* Url
* Load button
