### ISSUE TITLE
Add the data source and license information

### ISSUE THREAD

**Issue by lehtojaa** [GispoCoding/FMI2QGIS#2]
The main dialog window should include: 
- Include link to the datasource information 
- attribution to FMI as the source of the downloaded data (full information can be given in a separate window, or similar?)

In the [getCapabilities document](https://opendata.fmi.fi/wfs?request=GetCapabilities&storedquery_id=GetDataSetById&datasetid=1000571 ), one can find, for example, the following:

> <ows:AccessConstraints> 1.7.2014 1. General The use of the material is governed by the terms and conditions specified in this licence. The following are regarded as the producer of open data and the holders of copyright or database rights: the Finnish Meteorological Institute, the Finnish Transport Agency and other data producers as specified in Annex 1 (hereinafter the licensors). When used, the material or the service including or utilising the material must be accompanied by information on the original source and the date of the current version as follows: - the producer of the material and the retrieval date; - a note if the data have been adapted...  
> ...The licensee's obligations and responsibilities When using and transmitting the material or products made of the material, the licensee must: - mention the original source of the material in accordance with Section 1. General; - present a copy of this licence or a link to it; - require that the attribution practice specified under Section 1. General of this licence is followed when the licensee grants licenses to a product or service that uses some or all of the material subject to this licence; remove the note of the original source if so required explicitly by the licensor.  </ows:AccessConstraints>

**Comment by lehtojaa** [comment]
Link also to the correct air quality index definition (for example, add link next to the parameter selection). Enfuser data uses Finnish definition of AQI: https://en.ilmatieteenlaitos.fi/air-quality-index

**Comment by Joonalai** [comment]
@JaakkoLehto also a mention about financial supporters would be good.

**Comment by Joonalai** [comment]
It was decided to add mention about supporter to README.md and metadata.txt description.
