### ISSUE TITLE
Publish plugin to repository

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/FMI2QGIS#26]
- [x] Update metadata.txt with tags and description
- [x] Update README.md with description as well
- [ ] Add and use icon
- [x] Add initial plugin version to the repository manually
- [x] Configure CD

**Comment by Joonalai** [comment]
@anniinakovalainen could you design some kind of logo for the plugin?

**Comment by anniinaiikkanen** [comment]
@Joonalai is this okay?

![FMI2QGIS_logo_24x24](https://user-images.githubusercontent.com/51991990/99542022-3aacef80-29ba-11eb-879c-b660e08b1c20.png)

![FMI2QGIS_logo_1000x1000](https://user-images.githubusercontent.com/51991990/99542024-3b458600-29ba-11eb-916d-419e475106d7.png)

**Comment by Joonalai** [comment]
@anniinakovalainen perfect, thank you! :smile:
