### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by Joonalai** [GispoCoding/FMI2QGIS#32]
TBA.

**Comment by lehtojaa** [comment]
For WFS layers: 
 - Make window modal (not freezing the QGIS main window) to be able, for example, to adjust canvas and so on.
 - The dialog elements should be placed more compactly. For example, the buttons should be smaller, not window-wide.
 - Make the "Add data to canvas" check-box functional.
 - Set responsive items to unresponsive state while loading data.
