### ISSUE TITLE
Add dialog for WFS queries

### ISSUE THREAD

**Issue by lehtojaa** [GispoCoding/FMI2QGIS#4]
- In addition to main dialog for downloading and adding ENFUSER data in the NetCDF format, there should be, for example, a separate tab for downloading vector data through a WFS query.
- This could enable downloading (simple & complex features) and adding data (simple features) from all the layers corresponding to stored queries: https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=listStoredQueries 
- UI in this case should be adjusted automatically to each query.

**Comment by tjukanovt** [comment]
Fixed in previous release
