### ISSUE TITLE
Add documentation 

### ISSUE THREAD

**Issue by lehtojaa** [GispoCoding/FMI2QGIS#40]
Initially, this should at least include:
- general information and instructions to how to install and start using the plugin
- example cases: which stored queries to use (are tested to work) and with example parameters that are guaranteed to work

**Comment by lehtojaa** [comment]
It would also be good to add some instructions how to use the temporal controller with FMI2QGIS plugin.

**Comment by Joonalai** [comment]
Some GIF-animations would be great as well like here: https://gis.stackexchange.com/a/379144/123927
