### ISSUE TITLE
ENFUSER loading error: request failed with status code 400

### ISSUE THREAD

**Issue by tjukanovt** [GispoCoding/FMI2QGIS#57]
Some queries return error with status code 400. For example a simple query for ENFUSER data just returns 'Request failed with status code 400':
![image](https://user-images.githubusercontent.com/13899537/111307863-ac443400-8662-11eb-954e-0eb06bb165b3.png)

Query for this was as follows:
`Download url is is: "https://opendata.fmi.fi/download?producer=enfuser_helsinki_metropolitan&format=netcdf&starttime=2021-03-16T14:20:00Z&endtime=2021-03-17T14:20:00Z&bbox=-1.99,-1.0,1.99,1.0&param=AQIndex"`

Implementation workflow:
- [ ] Make sure that user gets more meaningful error message
- [ ] Validate user given parameters before starting the download
- [ ] Write test if possible

**Comment by Joonalai** [comment]
Most of the 400 errors are related to the bounding box. See #13.

**Comment by Joonalai** [comment]
Most of these are solved via #13.
