### ISSUE TITLE
Add NetCDF as mesh rather than raster

### ISSUE THREAD

**Issue by tjukanovt** [GispoCoding/FMI2QGIS#62]
Visualizations and temporal controller seem to work better if NetCDF is added to QGIS in mesh format rather than raster. [Working with mesh data](https://docs.qgis.org/3.16/en/docs/user_manual/working_with_mesh/mesh_properties.html)

Needs investigation. 

![image](https://user-images.githubusercontent.com/13899537/114698807-2df1b500-9d28-11eb-9a27-d375db85e67b.png)

**Comment by Joonalai** [comment]
I succeed to add NETCDF files with single variable, or files with multiple variables, but only one time step. For other files I only get the time_bounds as variable. I think we might have to wait until GDAL version is >= 3.1 with QGIS to get this tool [gdalmdimtranslate](https://gdal.org/programs/gdalmdimtranslate.html) that could solve the issues.

**Comment by tjukanovt** [comment]
@Joonalai This seems like a sensible approach. Let's keep this open until further notice.
